steps:
-   name: 'gcr.io/$PROJECT_ID/zip'
    args: ['-r', 'fod-payload.zip', '.']

-   name: 'gcr.io/$PROJECT_ID/fod-uploader'
    args: ['-portalurl', 'https://ams.fortify.com/', '-apiurl', 'https://api.ams.fortify.com/', '-ac', '257cf044-00c6-4029-9086-d74ce8a7727d', 'aG5LUUxQTGdqZ0tuRTY0aS1wVnJIWjA0LV1HYVEw0', '-tc', 'FranklinBank', '-z', 'fod-payload.zip', '-rid', '274581', '-ep', '2', '-pp', '0', '-I', '1', '-apf']
  